# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
project 'TakuSDKDemo.xcodeproj'

def share_pods
  
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MJRefresh'


end

target 'TakuSDKDemo' do
  
  post_install do |installer|
        installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
        end
      end
  
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  share_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'AnyThinkiOS','6.3.75'
  pod 'AnyThinkMaioSDKAdapter','6.3.75'
  pod 'AnyThinkStartAppSDKAdapter','6.3.75'
  pod 'AnyThinkBaiduSDKAdapter','6.3.75'
  #Baidu--4.80 SDK,podfile文件顶部增加 source 'https://github.com/CocoaPods/Specs.git'
  pod 'AnyThinkKuaiShouSDKAdapter','6.3.75'
  pod 'AnyThinkSigmobSDKAdapter','6.3.75'
  pod 'AnyThinkVungleSDKAdapter','6.3.75'
  pod 'AnyThinkUnityAdsSDKAdapter','6.3.75'
  pod 'AnyThinkIronSourceSDKAdapter','6.3.75'
  pod 'AnyThinkTapjoySDKAdapter','6.3.75'
  pod 'AnyThinkTTSDKAdapter','6.3.75'
  pod 'AnyThinkAdColonySDKAdapter','6.3.75'
  pod 'AnyThinkKlevinSDKAdapter','6.3.75'
  pod 'AnyThinkJDSDKAdapter','6.3.75'
  pod 'AnyThinkKidozSDKAdapter','6.3.75'
  pod 'AnyThinkJDSDKAdapter','6.3.75'
  pod 'AnyThinkFacebookSDKAdapter','6.3.75'
  pod 'AnyThinkAdmobSDKAdapter','6.3.75.1'
  pod 'AnyThinkInmobiSDKAdapter','6.3.75'
  pod 'AnyThinkApplovinSDKAdapter','6.3.75'
  pod 'AnyThinkMintegralSDKAdapter','6.3.75'
  pod 'AnyThinkGDTSDKAdapter','6.3.75'
  pod 'AnyThinkChartboostSDKAdapter','6.3.75'
  pod 'AnyThinkMyTargetSDKAdapter','6.3.75'
  pod 'AnyThinkFyberSDKAdapter','6.3.75'



end 
