# Recommend using GitHub source. Please check if terminal proxy network is accessible before pod install. If failed, try using pod install --repo-update command
source 'https://github.com/CocoaPods/Specs.git'

# The minimum supported iOS version should be determined based on the specific third-party advertising platform SDK version selected
platform :ios, '13.0'

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
end

target 'SwiftDemo' do
  use_frameworks!
  
  #Taku SDK
  pod 'AnyThinkiOS','6.4.93'

  #DebugUI,调试时建议接入,上线后去掉
  pod 'AnyThinkDebugUISDK','1.0.6'
  
  #为了降低Demo首次pod安装时间，Demo并未完整列举所有Adapter适配器的安装，若您需要使用自己的AppID/AppKey进行测试，请替换您选用的Adapter适配器后，重新执行pod install --repo-update安装
  
  #Demo所用适配器，若想使用更多广告平台，请前往SDK下载中心获取:https://app.takuad.com/m/sdk/download?type=iOS
  pod 'AnyThinkBaiduSDKAdapter','6.4.93'
  #Baidu--4.80 SDK,podfile文件顶部增加 source 'https://github.com/CocoaPods/Specs.git'
  pod 'AnyThinkKuaiShouSDKAdapter','6.4.93'
  pod 'AnyThinkTTSDKAdapter','6.4.93'
  pod 'AnyThinkGDTSDKAdapter','6.4.93'
  pod 'AnyThinkAdmobSDKAdapter','6.4.93'
 
  #Admob Interactive-media-ads广告类型,iOS13+
  pod 'AnyThinkIMASDKAdapter','6.4.93'

 
  # Third-party analytics SDKs
#  pod 'AppsFlyerFramework'
#  pod 'Adjust'
#  pod 'FirebaseAnalytics'
 
 # Third-party libraries for Demo UI dependencies
  pod 'SnapKit'
  pod 'SDWebImage'
  pod 'MJRefresh'
 
end
